### ISSUE TITLE
[Feature request] send email replies via "reply"

### ISSUE THREAD

**Issue by thomassth** [Pjaijai/Referalah#100]
There should be some way that can include sender's email into sender field, so I can reply with ease.

**Comment by Pjaijai** [comment]
Could you please elaborate your idea ? 
Do you mean receiver can reply the email directly ?

**Comment by yaucp** [comment]
I think he's talking abt Reply-To header?

**Comment by yaucp** [comment]
looks doable. should we proceed?

**Comment by Pjaijai** [comment]
@yaucp @thomassth  Sure, please assign the issue to yourself when you start working it

**Comment by Pjaijai** [comment]
Close for completion
