### ISSUE TITLE
Improve typing for better development experience

### ISSUE THREAD

**Issue by tommyttf** [Pjaijai/Referalah#116]
Now quite a few places is using `as` or not adding generic type for type already been defined

Should try add more for better static typing

**Comment by tommyttf** [comment]
0de34ad2 for `client/types/supabase.ts`, follow https://supabase.com/docs/guides/api/rest/generating-types to update it

`npx supabase gen types typescript --project-id "$PROJECT_REF" --schema public > types/supabase.ts`

**Comment by Pjaijai** [comment]
The issue has been resolved and is now closed.
