### ISSUE TITLE
[Feature Request] Add UK

### ISSUE THREAD

**Issue by yaucp** [Pjaijai/Referalah#118]
UK should be added as it is also a popular choice for other HKers as well

**Comment by 14104647ls3** [comment]
How about Australia as well?

**Comment by Pjaijai** [comment]
> How about Australia as well?

No problem. But we need to make the system flexible so that we can include all the people on the earth.

**Comment by Pjaijai** [comment]
Will do on coming phrase

**Comment by Pjaijai** [comment]
Done. Will add more cities in future
