### ISSUE TITLE
Infinite scroll not working properly

### ISSUE THREAD

**Issue by 511234** [Pjaijai/Referalah#127]
There's too few results (only 30~50) for prod `/post/referee` considering we have more than 1000 members and many of which should be referees.

<img width="1501" alt="infinitescroll" src="https://github.com/Pjaijai/Referalah/assets/76647602/978ea310-8210-4721-9ed0-c9303cb03b57">

For some reasons backend stops fetching data when there're 42 results.

**Comment by Pjaijai** [comment]
I'm quite sure that's not a technical issue 
哭咗

**Comment by 511234** [comment]
why's that?

**Comment by Pjaijai** [comment]
> why's that?

For referee post， 真係少人post
Most of them are in /referee
