### ISSUE TITLE
[Password Auth] Sign Up

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#147]
1. Email field[1]
2. username field
3. Password field [2]
4. Confirm password field [3]
5. A button to allow magic link register (Remove, no allow in sign up)
6. Check box to agree T&C and private policy (both should be a link redirecting to that pages)
7. Button redirect to Sign in page
[1] Must be in email format
[2] At least 8 character, max  20 character.
[3] Should be same as password

Design : https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=143%3A1669&mode=design&t=FvpNct0lrnE9McoY-1

After signing up, should tell user to check email to verify their email

bonus:
A. Clicking a button can show password value

B. Error handling for email duplication
1. Email duplication error
2. Generic sign up error 
3. Same username error

**Comment by thomassth** [comment]
This might be the prime time to implement and use PassKey, as most Android and iPhones, Windows and Mac are ready for it.

Example library:

https://oslo.js.org/reference/webauthn/

**Comment by Pjaijai** [comment]
@thomassth Sorry, what's that for ?

**Comment by thomassth** [comment]
It's made to replace password

basically you can do biometrics on your phone to login a website, without building an app. It even works on old PCs (with your phone on hand)

Demo website: https://www.passkeys.io/

**Comment by Pjaijai** [comment]
> It's made to replace password
> 
> basically you can do biometrics on your phone to login a website, without building an app. It even works on old PCs (with your phone on hand)
> 
> Demo website: https://www.passkeys.io/

Cool. Will take a look of it

**Comment by Pjaijai** [comment]
@thomassth Currently supabase dose not support this https://github.com/orgs/supabase/discussions/8677. Is there any way to implement this with low cost ?

**Comment by yaucp** [comment]
@Pjaijai can use this atm: https://supabase.com/partners/integrations/passageidentity
but need to pay: https://passage.1password.com/pricing

**Comment by Pjaijai** [comment]
> @Pjaijai can use this atm: https://supabase.com/partners/integrations/passageidentity
> 
> but need to pay: https://passage.1password.com/pricing

I'm considering

**Comment by Pjaijai** [comment]
Created PR https://github.com/Pjaijai/Referalah/pull/269. It is a logic skeleton. Will finalize after the design is ready. @yannyyau

**Comment by Pjaijai** [comment]
Done
