### ISSUE TITLE
[Post History] Creating Post detail page

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#152]
Currently we do not have post detail page.

1. Creating an api getPostByUuid
2. Creating dynamic post detail page
3. If the post status is not 'active' and it is 'inactive', display something like  `不再受理`

**Comment by marukosy124** [comment]
I think create and edit post should share the same page, so it would be better if the same person works on both issues #152 and  #154 . I can take both issues if you are okay.

**Comment by marukosy124** [comment]
Can I work on this issue?

**Comment by Pjaijai** [comment]
@marukosy124 Yes, Please assign to yourself when you get started working on it

**Comment by Pjaijai** [comment]
Done
