### ISSUE TITLE
[Mobile friendly] Design a new UXUI for mobile user 

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#158]
Based on analytics tool, 60% of user are using mobile to access this web.

We should revamp or modify UXUI for mobile user.

**This issue should be split into several small issues after discussion**

**Comment by Pjaijai** [comment]
Problem
1. Back to previous page button

**Comment by yannyyau** [comment]
Issues:
1. Actions & Navigation (Pages) mix together in top navigation 
2. Unable to go back on pages "用戶檔案" & "街招"
3. Top navigation disappears on pages “推薦人”, ”受薦人”, “街招” in mobile mode

**Comment by Pjaijai** [comment]
Done
