### ISSUE TITLE
SEO optimization

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#164]
Currently we use one title for all pages.
We need to make seo better by adding dynamic seo

**Comment by ken999999999999999** [comment]
I found this doc : https://nextjs.org/docs/pages/api-reference/components/head, hope it can help

**Comment by Pjaijai** [comment]
@ken999999999999999  Many Thanks. Will get started working on this later

**Comment by 511234** [comment]
- [ ] Relocate 'use client' to react components
- [ ] Store metadata in `config/site.ts` for easier management 
- [ ] Add metadata using `generateMetadata`
- [ ] Create dynamic metadata content from page params
- [ ] Build sitemap? (I haven't done this before, idk how to do it / if it's necessary, will do some research later)
- [ ] Any other business

Ref:   
Next.js:  
[Next.js / App Router / Building Your Application / Optimizing / Metadata](https://nextjs.org/docs/app/building-your-application/optimizing/metadata)

Similar websites:  
[Refer Me](https://www.refer.me/)

**Tentative metadata (please, comment & advice!) :)**
I get Chinese version from `/components/navigation-menu/base.tsx` and try to translate them to English.


| Route                 | Title                                                  | Description                                                                                                                                                                        |
|-----------------------|--------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| /                     | Referalah \| 海外港人搵 Referral 平台                  | 海外港人搵Referral平台。 A job referral platform for overseas Hongkongers. Connect, refer and get referred to support the Hong Kong community across the globe.                    |
| /about                | 理念 About Us \| Referalah                             | 海外搵工好多時都需要人脈，有人推薦先有面試，而外地愈嚟愈多港人，但缺乏相關文化同平台。呢個平台喺俾大家搵翻同聲同氣嘅，無論你係藍領白領，都希望大家互相幫忙。                       |
| /auth                 | 登入 / 註冊 Sign In / Sign Up \| Referalah             | 透過魔術連結登入或註冊。無須密碼。 Sign in or sign up with magic link. Password is not required.                                                                                   |
| /post/create          | 貼街招 Stick a job posting \| Referalah                | 你公司請人又想搵香港人？網上睇到份工又想人幫手？係到貼個街招，等人聯絡你。 Is your company hiring and looking for folks from Hong Kong? Stick a job posting here to get contacted. |
| /post/referee         | 人搵工 Job searching \| Referalah                      | 係到搵有乜人需要幫手。 Lend a helping hand to those who need a referral for a job posting.                                                                                         |
| /post/referer         | 工搵人 Job hiring \| Referalah                         | 係到搵有乜工搵人推薦。 Look for job postings and get referred.                                                                                                                     |
| /privacy-policy       | 隱私權政策 Private Policy \| Referalah                 | 海外港人搵Referral平台。 A job referral platform for overseas Hongkongers. Connect, refer and get referred to support the Hong Kong community across the globe.                    |
| /profile/[userUuid]       | {{ user.username }} 用戶檔案 User Profile \| Referalah | {{ user.description }}                                                                                                                                                             |
| /referee              | 受薦人 Referees \| Referalah                           | 想搵人材？係到睇下有冇合適嘅人啦！ Recommend an amazing talent from Hong Kong to join your company!                                                                                |
| /referer              | 推薦人 Referers \| Referalah                           | 想搵人推薦你入去？係到搵下啦！ Meet someone to bring you closer to your dream company!                                                                                             |
| /terms-and-conditions | 條款及細則 Terms and Conditions \| Referalah           | 海外港人搵Referral平台。 A job referral platform for overseas Hongkongers. Connect, refer and get referred to support the Hong Kong community across the globe.                    |
| (default)             | Referalah \| 海外港人搵 Referral 平台                  | 海外港人搵Referral平台。 A job referral platform for overseas Hongkongers. Connect, refer and get referred to support the Hong Kong community across the globe.                    |

**Comment by Pjaijai** [comment]
@511234  工搵人  will be removed

**Comment by Pjaijai** [comment]
@511234 btw 原來有公司做呢啲野 不過要課金

**Comment by 511234** [comment]
> @511234 工搵人 will be removed

ok! Haven't come back for a few weeks, need to catch up with new code. :-)

**Comment by Pjaijai** [comment]
> > @511234 工搵人 will be removed
> 
> ok! Haven't come back for a few weeks, need to catch up with new code. :-)

Nvm take your time. Happy coding

**Comment by Pjaijai** [comment]
Ahh should be 人搵工. 人搵工 already removed sor.

**Comment by Pjaijai** [comment]
Please add your self into contributors page

**Comment by Pjaijai** [comment]
Done
