### ISSUE TITLE
[Referral post card] Avatar and button are not center-aligned when the avatar has image

### ISSUE THREAD

**Issue by marukosy124** [Pjaijai/Referalah#184]
<img width="274" alt="Screenshot 2023-10-30 at 1 37 11 PM" src="https://github.com/Pjaijai/Referalah/assets/54564324/8a55e0e2-16a6-4afe-86da-e5e682cb8a3c">
This only happens when the avatar has image

**Comment by Pjaijai** [comment]
This pr is going to simplify the card https://github.com/Pjaijai/Referalah/pull/185. The button will be removed since we already have a post detail page
