### ISSUE TITLE
[Error Handling] Create Error boundary 

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#204]
We need to error boundary to wrap the template components in page level in case the error destroy the whole frontend experience.
If the component throw, we need to display something like "AHH Error sorry ah, maybe you try try refresh"

Reference : https://legacy.reactjs.org/docs/error-boundaries.html
Maybe we can use this library : https://github.com/bvaughn/react-error-boundary or write our own handling

**Comment by ken31ee** [comment]
Should we use the error boundary from Nest.js?
Reference: [https://nextjs.org/docs/app/building-your-application/routing/error-handling](https://nextjs.org/docs/app/building-your-application/routing/error-handling)

**Comment by Pjaijai** [comment]
> Should we use the error boundary from Nest.js? Reference: https://nextjs.org/docs/app/building-your-application/routing/error-handling

Yea sure

**Comment by Pjaijai** [comment]
Please add yourself to the contributor page

**Comment by paco0161** [comment]
Let me work on it
