### ISSUE TITLE
[Edit Post] Minor issues with the edit post page

### ISSUE THREAD

**Issue by marukosy124** [Pjaijai/Referalah#205]
### BUG
https://github.com/Pjaijai/Referalah/assets/54564324/d2fd8baf-bb78-495e-86ea-41fbd9063d6a

Cannot clear the url when: double click to select all -> backspace

### UI
<img width="867" alt="Screenshot 2023-11-05 at 5 23 17 PM" src="https://github.com/Pjaijai/Referalah/assets/54564324/a35e1fc3-c229-4287-b26c-65e9ef3d9db7">
<img width="867" alt="Screenshot 2023-11-05 at 5 22 47 PM" src="https://github.com/Pjaijai/Referalah/assets/54564324/bafa6be9-4a3b-47c4-afa2-a5857d7e8b09">

Prefer to add a title (e.g.更改街招）on the edit post page so that it is consistent with the create post page

**Comment by Pjaijai** [comment]
Will do

**Comment by tommyttf** [comment]
For the bug,

https://github.com/Pjaijai/Referalah/blob/development/client/modules/post/edit/template.tsx#L84

should related to the useEffect of `form.watch`
same issue happened to yeo field

after I comment the hook, can simple clear the field, 
but not sure is there anything else to consider as it was for the field to be optional 
https://github.com/Pjaijai/Referalah/commit/6a0e0678

**Comment by marukosy124** [comment]
@Pjaijai @tommyttf I tried to remove the hook -> clear the URL field -> submit the form, it works fine and the URL can be cleared in the db. So maybe just remove the hook.

**Comment by tommyttf** [comment]
I removed the useEffect
Also default disable pwa in dev mode
