### ISSUE TITLE
[Create Post] Should redirect user to post detail page instead of referrer page after creating a new post

### ISSUE THREAD

**Issue by marukosy124** [Pjaijai/Referalah#213]
<img width="867" alt="Screenshot 2023-11-06 at 2 03 33 PM" src="https://github.com/Pjaijai/Referalah/assets/54564324/a2d2a6aa-a4a7-425d-95cc-dd4ff11f7cd7">

Currently onSuccess of the create post form will redirect user to referrer page, which is weird in terms of the user flow.

**Comment by cyruscsc** [comment]
The main difficulty seems to be not getting the new post data as a response upon creating a post successfully. It is hard to redirect the user to the new post without its uuid. 

I found the `.select()` method from [supabase doc](https://supabase.com/docs/reference/javascript/insert?example=create-a-record-and-return-it). It may help, but I still haven't figured out the best way to implement it in our code.

**Comment by marukosy124** [comment]
@cyruscsc I think the uuid can be retrieved from `{ data }` as mentioned in the [docs](https://supabase.com/docs/reference/javascript/insert)

**Comment by Pjaijai** [comment]
Your are right. Since we dont have detail post page that time

**Comment by Pjaijai** [comment]
@cyruscsc I supabase will return the data after creating ? 

https://supabase.com/docs/reference/javascript/insert

`
const { data, error } = await supabase
  .from('countries')
  .insert({ id: 1, name: 'Denmark' })
  .select()`

**Comment by marukosy124** [comment]
@Pjaijai I think you can just return the uuid by `.select("uuid")` as you don't really need the details? You will call GET API in the details page anyway

**Comment by Pjaijai** [comment]
@marukosy124  @cyruscsc Created a PR please check https://github.com/Pjaijai/Referalah/pull/230

**Comment by Pjaijai** [comment]
Done
