### ISSUE TITLE
[Navbar] UI Issues

### ISSUE THREAD

**Issue by marukosy124** [Pjaijai/Referalah#220]
### Issues
- The nav menu in the middle is not center-aligned
<img width="1003" alt="Screenshot 2023-11-07 at 9 30 25 AM" src="https://github.com/Pjaijai/Referalah/assets/54564324/b3b35516-b154-455a-bdfb-ea809bfbe146">

- User dropdown menu:
  - On desktop screen size, 推薦人，受薦人，貼街招，工搵人 are already shown in the dropdown menu in the middle, showing them in the user dropdown menu again may be confusing
  - 工搵人 should be 街招 instead as we don't have different types of 街招 now
  - Suggest to use a divider or different text color to differentiate the "logout" button and other links
<img width="306" alt="Screenshot 2023-11-07 at 9 27 55 AM" src="https://github.com/Pjaijai/Referalah/assets/54564324/4b1a03e4-770d-4ed0-aa9a-fa6652468b9c">

**Comment by cyruscsc** [comment]
I created a new branch to do this cuz the original one was not based on development branch

**Comment by cyruscsc** [comment]
Done
