### ISSUE TITLE
[Post Card] Minor UI bugs

### ISSUE THREAD

**Issue by marukosy124** [Pjaijai/Referalah#226]
- Created date does not stick to the bottom
<img width="1386" alt="Screenshot 2023-11-07 at 5 59 55 PM" src="https://github.com/Pjaijai/Referalah/assets/54564324/c71969aa-4cac-4503-9312-430e1d08a0c6">

- link tooltip is not center-aligned with the icon
<img width="152" alt="Screenshot 2023-11-07 at 6 05 16 PM" src="https://github.com/Pjaijai/Referalah/assets/54564324/c6831bf4-fc7d-41ef-b4b7-f7a3ed34c6ca">

**Comment by Pjaijai** [comment]
Done
