### ISSUE TITLE
[SEO] Add 'rel=nofollow' for any external links a tag

### ISSUE THREAD

**Issue by tommyttf** [Pjaijai/Referalah#235]
For all the external links `a` tag, it should add `rel="Nofollow"` in the tag attribute, in case there is someone using our website for spam

Like the one in job post header, it should look like `<a target="_blank" rel="nofollow" title="XXX" href="YYY">`

Might need to check all the links in our website about this, not sure is there any handling about this in nextjs

https://en.wikipedia.org/wiki/Nofollow

**Comment by tommyttf** [comment]
can also refer to this
https://pointjupiter.com/what-noopener-noreferrer-nofollow-explained/

we should also add `rel= "noopener"` for those <a /> with `target="_blank"`

**Comment by Pjaijai** [comment]
For those <Link/> component which containing user defined url, we can use router.push to fix this problem which will not create a <a/> tag

reference:
https://stackoverflow.com/questions/65086108/next-js-link-vs-router-push-vs-a-tag

**Comment by Pjaijai** [comment]
Done
