### ISSUE TITLE
[In-app chat] Notifications

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#242]
Design:

1. Design a way that user can check all the notifications

Tech:

1. Implementing Notification pushing using Firebase or [Knock](https://knock.app/).

We need to discuss do we need to fully transfer email to in-app chat. If user does not turn on notification permission, how do we handle this case. Sending Email instead ? Or Just minding user to grant permission (of course providing guidelines)

**Comment by Pjaijai** [comment]
If we choose Firebase, then we need to create notification history table

**Comment by Pjaijai** [comment]
A. Email
B. In-app notification

For in-app chat:
1. Push A and B in first contact
2. Push A to remind unread message  

Type:
Referral contact  
new job -> referrer

**Comment by heleninsane** [comment]
https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=665-4583&mode=design&t=0UVygqEmFewlHE8H-4

UI ready for review.

**Comment by Pjaijai** [comment]
Gave up
