### ISSUE TITLE
[In-app chat] Chat room page

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#243]
The scope of this issue does not include sending message. Just the UI

Design:

1. Design an UI for chat room.  
2. To shape how does the message look like

Tech

1. The chat room page should display all the chats.
3. The chat is 1 on 1 chat. Not allow group chat.

**Comment by Pjaijai** [comment]
- Can continue conversation after other user reply.

**Comment by heleninsane** [comment]
Updated [UI](https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=288-2413&mode=design&t=mQ2QJE87ZDE4rK1z-4)

**Comment by Pjaijai** [comment]
Done
