### ISSUE TITLE
[Refactor] Filter reset button ambiguous

### ISSUE THREAD

**Issue by VardyNg** [Pjaijai/Referalah#251]
![image](https://github.com/Pjaijai/Referalah/assets/24868846/a6edadc5-1d77-425b-87b1-053f35206e7c)

The "Reset" button here seems ambiguous to me, it looks like a "Reload" button. I think it is best to put it inside the filter menu.

Also, add indication to the "Filter" button to indicate some filter rules are applied.

**Comment by Pjaijai** [comment]
Need designer help and discussion for the filter and reset button

**Comment by Pjaijai** [comment]
done
