### ISSUE TITLE
[Mobile friendly] Removing actions from nav tap

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#262]
Suggest to remove actions “成為推薦人/受薦人” & “貼街招” from top nav.

credit @yannyyau

**Comment by selin4242** [comment]
Updated : [https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=529-6947&mode=design&t=fq64EfNQ7UXkGE1u-11](url)

**Comment by Pjaijai** [comment]
No question for me.
@heleninsane @yannyyau @twinintwinkle please take a look

**Comment by heleninsane** [comment]
On Top nav, as considering to have next stage of implementation, I would recommend to have notification center icon button as well.

**Comment by yannyyau** [comment]
In later stage, I think it will be better to move both actions "成為推薦人/受薦人" and "貼街招" as buttons on the pages of "推薦人", "受薦人" and "街招", instead of showing these two on navigation. Especially for "成為推薦人/受薦人" as it will lead to sign up/log in/edit profile page, which all have their own separate buttons/links on the website. For reference, can take a look on Google reviews & FB Marketplace.

**Comment by selin4242** [comment]
@heleninsane @Pjaijai , Would recommend the chat + not instead of just noti, as chat is an important function in the referral process. updated the design. [https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=526-6419&mode=design&t=eHIUUvRJxnmXcpRQ-11](url)

**Comment by selin4242** [comment]
@yannyyau 

> In later stage, I think it will be better to move both actions "成為推薦人/受薦人" and "貼街招" as buttons on the pages of "推薦人", "受薦人" and "街招", instead of showing these two on navigation. Especially for "成為推薦人/受薦人" as it will lead to sign up/log in/edit profile page, which all have their own separate buttons/links on the website. For reference, can take a look on Google reviews & FB Marketplace.

I think the team can discuss this in the next meeting to decide 1. are we gonna have these CTAs on both mobile & desktop p. 2. Should the page be changed after they log in 3. What page will these CTAs bring users to? It's hard to decide without knowing the use cases @Pjaijai

**Comment by Pjaijai** [comment]
Done
