### ISSUE TITLE
[Mobile friendly] Adding a go back button

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#264]
We have no way to let user to go back to previous page

credit @yannyyau

**Comment by selin4242** [comment]
Updated : [https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=529-6947&mode=design&t=fq64EfNQ7UXkGE1u-11](url)

**Comment by Pjaijai** [comment]
Done
