### ISSUE TITLE
[Mobile friendly] Adding menu for mobile

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#265]
Problem : Top navigation disappears on pages “推薦人”, ”受薦人”, “街招” in mobile mode

Suggest to add hamburger menu in mobile mode

credit @yannyyau

**Comment by selin4242** [comment]
updated[https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=529-6947&mode=design&t=fq64EfNQ7UXkGE1u-11](url)

**Comment by Pjaijai** [comment]
> updated[https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=529-6947&mode=design&t=fq64EfNQ7UXkGE1u-11](url)

No question for me.
@heleninsane @yannyyau @twinintwinkle please take a look

**Comment by Pjaijai** [comment]
@selin4242 btw please check discord dm or message me on tg. Thank you

**Comment by heleninsane** [comment]
Looks legit to me.

**Comment by yannyyau** [comment]
Added suggestions on figma file, thanks!

**Comment by marukosy124** [comment]
@yannyyau @heleninsane @selin4242 So for [this screen](https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=526-6525&mode=design&t=tOuzIo9aBXKHMuNr-0), is the chat icon inside the menu or not?

**Comment by selin4242** [comment]
@yannyyau @heleninsane Thanks for the feedback,Please take a look of the replies. @marukosy124 the chat icon inside both the top nav bar and the side menu.

**Comment by Pjaijai** [comment]
Done
