### ISSUE TITLE
[Mobile friendly] Re-designing user profile (edit & public profile)

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#291]

**Comment by yannyyau** [comment]
Design drafted in figma file, under "Sign Up & Edit Profile Flow".
https://www.figma.com/file/ejXkHD7sbaCaNDbJexDtvt/Referalah-Working-File?type=design&node-id=115%3A324&mode=design&t=JKyT1GFYDgF1Xtir-1

**Comment by Pjaijai** [comment]
For the collapsed section, they are default open or closed?

@heleninsane @twinintwinkle @selin4242  Please take look if you have time.

**Comment by heleninsane** [comment]
Looks good to me. Thank you!

**Comment by yannyyau** [comment]
for mobile, i think default closed section to avoid long form & give user an overview at first glance
one disadvantage is that users will have to make one more step before editing
what do you think?
