### ISSUE TITLE
Pressing enter in profile edit page loses all info

### ISSUE THREAD

**Issue by hulloanson** [Pjaijai/Referalah#318]
To reproduce:

1. Go to profile page
2. click edit
3. enter all required info
4. press enter when focused on any input
5. profile goes back to read-only mode without saving anything

**Comment by Pjaijai** [comment]
Thank you for submitting the issue.

**Comment by Pjaijai** [comment]
This PR will fix this issue
https://github.com/Pjaijai/Referalah/pull/320

**Comment by Pjaijai** [comment]
Should be fixed
