### ISSUE TITLE
Small chat page scrollbar behaviour change

### ISSUE THREAD

**Issue by terryleung00** [Pjaijai/Referalah#324]
Currently, the chat page will have 3 separate scrollbar
The rightmost one will control the whole body causing some info being block
![scrollbar](https://github.com/Pjaijai/Referalah/assets/90096118/c6644c31-839a-465d-93aa-5f3bf0da2ecf)

The fastest way to fix it is to force the height of the chat page from
`flex h-screen w-full flex-row overflow-hidden`
to
`flex h-[calc(100vh-65px)] w-full flex-row overflow-hidden`

but it requires a manual change in the future if the height of header is changed.

**Comment by Pjaijai** [comment]
Fixed. Many thanks
