### ISSUE TITLE
Adding testing libraries

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#74]
Adding Testing library like Jest and react-testing-library

**Comment by VardyNg** [comment]
As the project is in rapid development, I think it is best to first scaffold the test framework and workflow, as it is not realistic to complete all missing test cases before merging to the development branch.

After that, we could start adding the test cases for the existing code. At the mean time, the new code should comes with test cases.

**Comment by Pjaijai** [comment]
Added. Done
