### ISSUE TITLE
[Mobile friendly] PWA

### ISSUE THREAD

**Issue by Pjaijai** [Pjaijai/Referalah#94]
Making progressive web app so it can be an "app".

Reference:
https://dev.to/anuraggharat/pwa-with-nextjs-5178

**Comment by Pjaijai** [comment]
Need to make sure it is mobile friendly

**Comment by tommyttf** [comment]
should follow this article for nextjs 13 although the steps are almost the same 
https://dev.to/sabbir_zz/pwa-with-next-js-13-194l

just the library's last update is last year Dec, so really need to test about this 
https://github.com/shadowwalker/next-pwa

also will need app icon for the app display

**Comment by Pjaijai** [comment]
@tommyttf  Many Thanks

**Comment by 14104647ls3** [comment]
Please checkout PR #192 @tommyttf @Pjaijai

**Comment by Pjaijai** [comment]
done
