### ISSUE TITLE
Include LinkedIn & other social links into referral request emails

### ISSUE THREAD

**Issue by thomassth** [Pjaijai/Referalah#99]

**Comment by Pjaijai** [comment]
I am thinking user should set up their profile. When they send a request, the email will attached the user profile link.
Of course user profile route need to be changed to dynamic route.

**Comment by yaucp** [comment]
I think we can add the receiver's social media url (if they have one) in the email first for now?

**Comment by tommyttf** [comment]
For this, better change '個人連結(選填)' in the profile page to be able to input multiple links as well, like we software engineer would have linkedin, fithub, personal profile website, but now we can only put one of them in the field

**Comment by Pjaijai** [comment]
@tommyttf Great idea. Will create a issue for it

**Comment by Pjaijai** [comment]
created issue https://github.com/Pjaijai/Referalah/issues/166
